name: 'Postmark Action'
description: 'Send emails using Postmark API with template support'
author: 'Ashwin Khode <ashwin.khode1@gmail.com>'
branding:
  icon: 'mail'
  color: 'yellow'

inputs:
  postmark-token:
    description: 'Postmark API token'
    required: true
  to:
    description: 'Recipient email address'
    required: true
  from:
    description: 'Sender email address'
    required: true
  subject:
    description: 'Email subject'
    required: true
  body:
    description: 'Email body content (not required if using template)'
    required: false
  template-path:
    description: 'Path to the HTML template file'
    required: false
  template-data:
    description: 'JSON string containing template variables'
    required: false
  is-html:
    description: 'Whether the body content is HTML'
    required: true

outputs:
  status:
    description: 'Status of the email sending operation'
    
runs:
  using: 'node20'
  main: 'dist/index.js'