name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: pnpm-ci
        run: pnpm install --frozen-lockfile

      - name: Check Format
        id: pnpm-format-check
        run: pnpm run format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm run lint

      - name: Test
        id: pnpm-ci-test
        run: pnpm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action Without Template
        id: test-action-without-template
        uses: ./
        with:
          postmark-token: ${{ secrets.POSTMARK_TOKEN }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: 'Test Email Without Template'
          body: 'This is a test email without template'
          is-html: false

      - name: Test Local Action With Template
        id: test-action-with-template
        uses: ./
        with:
          postmark-token: ${{ secrets.POSTMARK_TOKEN }}
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
          subject: 'Test Email With Template'
          is-html: true
          template-path: './templates/test.html'
          template-data: |
            {
              "name": "${{ secrets.NAME }}",
              "age": 25,
              "gender": "male"
            }

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
